# Generated by Django 3.1.1 on 2020-09-18 15:02

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(auto_created=True, default=utils.random_string, editable=False, max_length=10),
        ),
    ]
