# Generated by Django 3.1.1 on 2020-09-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_manager_nurse_receptionist'),
        ('appointment', '0003_auto_20200918_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receptionist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user.receptionist'),
            preserve_default=False,
        ),
    ]
