# Generated by Django 3.1.1 on 2020-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('U', 'URGENT_APPOINTMENT'), ('R', 'ROUTINE_APPOINTMENT'), ('H', 'HOME_VISIT_APPOINTMENT')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
